version: '3.3'

services:

  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf/hyperf:8.0-alpine-v3.13-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "start"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    depends_on:
      - hyperf-skeleton-mariadb

  hyperf-skeleton-mariadb:
    container_name: hyperf-skeleton-mariadb
    image: mariadb:latest
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "hyperf-skeleton"

 